import { db } from '@/db';
import { activityLogs } from '@/db/schema';

async function main() {
    const now = new Date();
    const thirtyDaysAgo = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);
    
    const getRandomDate = (start: Date, end: Date, isWeekday: boolean = true) => {
        const date = new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()));
        
        if (isWeekday) {
            const day = date.getDay();
            if (day === 0) date.setDate(date.getDate() + 1); // Skip Sunday
        }
        
        const hours = Math.floor(Math.random() * 10) + 8; // 8 AM - 6 PM
        const minutes = Math.random() < 0.5 ? 0 : 30;
        date.setHours(hours, minutes, 0, 0);
        
        return date.toISOString();
    };

    const users = [
        { userId: 'admin-001', userName: 'John Admin' },
        { userId: 'admin-002', userName: 'Sarah Manager' },
        { userId: 'admin-003', userName: 'Mike Coordinator' },
        { userId: 'admin-004', userName: 'Emily Supervisor' },
        { userId: 'admin-005', userName: 'David Controller' },
    ];

    const sampleLogs = [
        // FACULTY_ADDED (9 entries)
        {
            actionType: 'FACULTY_ADDED',
            userId: 'admin-001',
            userName: 'John Admin',
            timestamp: getRandomDate(thirtyDaysAgo, new Date(now.getTime() - 25 * 24 * 60 * 60 * 1000)),
            description: 'Faculty added: Dr. Robert Johnson',
            referenceType: 'faculty',
            referenceId: 1,
            previousValue: null,
            newValue: JSON.stringify({ id: 1, name: 'Dr. Robert Johnson', email: 'rjohnson@uni.edu', department: 'Computer Science' }),
            metadata: null,
            severity: 'success',
            isSystemAction: false,
            createdAt: getRandomDate(thirtyDaysAgo, new Date(now.getTime() - 25 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'FACULTY_ADDED',
            userId: 'admin-002',
            userName: 'Sarah Manager',
            timestamp: getRandomDate(thirtyDaysAgo, new Date(now.getTime() - 24 * 24 * 60 * 60 * 1000)),
            description: 'Faculty added: Dr. Emily Davis',
            referenceType: 'faculty',
            referenceId: 2,
            previousValue: null,
            newValue: JSON.stringify({ id: 2, name: 'Dr. Emily Davis', email: 'edavis@uni.edu', department: 'Mathematics' }),
            metadata: null,
            severity: 'success',
            isSystemAction: false,
            createdAt: getRandomDate(thirtyDaysAgo, new Date(now.getTime() - 24 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'FACULTY_ADDED',
            userId: 'admin-001',
            userName: 'John Admin',
            timestamp: getRandomDate(thirtyDaysAgo, new Date(now.getTime() - 23 * 24 * 60 * 60 * 1000)),
            description: 'Faculty added: Dr. Sarah Lee',
            referenceType: 'faculty',
            referenceId: 3,
            previousValue: null,
            newValue: JSON.stringify({ id: 3, name: 'Dr. Sarah Lee', email: 'slee@uni.edu', department: 'Physics' }),
            metadata: null,
            severity: 'success',
            isSystemAction: false,
            createdAt: getRandomDate(thirtyDaysAgo, new Date(now.getTime() - 23 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'FACULTY_ADDED',
            userId: 'admin-003',
            userName: 'Mike Coordinator',
            timestamp: getRandomDate(new Date(now.getTime() - 22 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 20 * 24 * 60 * 60 * 1000)),
            description: 'Faculty added: Dr. Michael Chen',
            referenceType: 'faculty',
            referenceId: 4,
            previousValue: null,
            newValue: JSON.stringify({ id: 4, name: 'Dr. Michael Chen', email: 'mchen@uni.edu', department: 'Chemistry' }),
            metadata: null,
            severity: 'success',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 22 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 20 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'FACULTY_ADDED',
            userId: 'admin-002',
            userName: 'Sarah Manager',
            timestamp: getRandomDate(new Date(now.getTime() - 19 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 17 * 24 * 60 * 60 * 1000)),
            description: 'Faculty added: Dr. Jennifer Brown',
            referenceType: 'faculty',
            referenceId: 5,
            previousValue: null,
            newValue: JSON.stringify({ id: 5, name: 'Dr. Jennifer Brown', email: 'jbrown@uni.edu', department: 'Biology' }),
            metadata: null,
            severity: 'success',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 19 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 17 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'FACULTY_ADDED',
            userId: 'admin-004',
            userName: 'Emily Supervisor',
            timestamp: getRandomDate(new Date(now.getTime() - 16 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 14 * 24 * 60 * 60 * 1000)),
            description: 'Faculty added: Dr. David Wilson',
            referenceType: 'faculty',
            referenceId: 6,
            previousValue: null,
            newValue: JSON.stringify({ id: 6, name: 'Dr. David Wilson', email: 'dwilson@uni.edu', department: 'Economics' }),
            metadata: null,
            severity: 'success',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 16 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 14 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'FACULTY_ADDED',
            userId: 'admin-001',
            userName: 'John Admin',
            timestamp: getRandomDate(new Date(now.getTime() - 13 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 11 * 24 * 60 * 60 * 1000)),
            description: 'Faculty added: Dr. Amanda Martinez',
            referenceType: 'faculty',
            referenceId: 7,
            previousValue: null,
            newValue: JSON.stringify({ id: 7, name: 'Dr. Amanda Martinez', email: 'amartinez@uni.edu', department: 'English' }),
            metadata: null,
            severity: 'success',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 13 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 11 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'FACULTY_ADDED',
            userId: 'admin-005',
            userName: 'David Controller',
            timestamp: getRandomDate(new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000)),
            description: 'Faculty added: Dr. James Taylor',
            referenceType: 'faculty',
            referenceId: 8,
            previousValue: null,
            newValue: JSON.stringify({ id: 8, name: 'Dr. James Taylor', email: 'jtaylor@uni.edu', department: 'History' }),
            metadata: null,
            severity: 'success',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'FACULTY_ADDED',
            userId: 'admin-003',
            userName: 'Mike Coordinator',
            timestamp: getRandomDate(new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000), now),
            description: 'Faculty added: Dr. Lisa Anderson',
            referenceType: 'faculty',
            referenceId: 9,
            previousValue: null,
            newValue: JSON.stringify({ id: 9, name: 'Dr. Lisa Anderson', email: 'landerson@uni.edu', department: 'Psychology' }),
            metadata: null,
            severity: 'success',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000), now),
        },

        // FACULTY_UPDATED (6 entries)
        {
            actionType: 'FACULTY_UPDATED',
            userId: 'admin-002',
            userName: 'Sarah Manager',
            timestamp: getRandomDate(new Date(now.getTime() - 20 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 18 * 24 * 60 * 60 * 1000)),
            description: 'Faculty updated: Dr. Emily Davis',
            referenceType: 'faculty',
            referenceId: 2,
            previousValue: JSON.stringify({ email: 'edavis@uni.edu', department: 'Mathematics' }),
            newValue: JSON.stringify({ email: 'emily.davis@uni.edu', department: 'Mathematics' }),
            metadata: null,
            severity: 'info',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 20 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 18 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'FACULTY_UPDATED',
            userId: 'admin-001',
            userName: 'John Admin',
            timestamp: getRandomDate(new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 13 * 24 * 60 * 60 * 1000)),
            description: 'Faculty updated: Dr. Robert Johnson',
            referenceType: 'faculty',
            referenceId: 1,
            previousValue: JSON.stringify({ department: 'Computer Science' }),
            newValue: JSON.stringify({ department: 'Computer Science & Engineering' }),
            metadata: null,
            severity: 'info',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 13 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'FACULTY_UPDATED',
            userId: 'admin-004',
            userName: 'Emily Supervisor',
            timestamp: getRandomDate(new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000)),
            description: 'Faculty updated: Dr. Sarah Lee',
            referenceType: 'faculty',
            referenceId: 3,
            previousValue: JSON.stringify({ email: 'slee@uni.edu' }),
            newValue: JSON.stringify({ email: 'sarah.lee@uni.edu' }),
            metadata: null,
            severity: 'info',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'FACULTY_UPDATED',
            userId: 'admin-003',
            userName: 'Mike Coordinator',
            timestamp: getRandomDate(new Date(now.getTime() - 9 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000)),
            description: 'Faculty updated: Dr. Michael Chen',
            referenceType: 'faculty',
            referenceId: 4,
            previousValue: JSON.stringify({ department: 'Chemistry' }),
            newValue: JSON.stringify({ department: 'Chemistry & Biochemistry' }),
            metadata: null,
            severity: 'info',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 9 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'FACULTY_UPDATED',
            userId: 'admin-005',
            userName: 'David Controller',
            timestamp: getRandomDate(new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000)),
            description: 'Faculty updated: Dr. Jennifer Brown',
            referenceType: 'faculty',
            referenceId: 5,
            previousValue: JSON.stringify({ email: 'jbrown@uni.edu' }),
            newValue: JSON.stringify({ email: 'jennifer.brown@uni.edu' }),
            metadata: null,
            severity: 'info',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'FACULTY_UPDATED',
            userId: 'admin-002',
            userName: 'Sarah Manager',
            timestamp: getRandomDate(new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000), now),
            description: 'Faculty updated: Dr. David Wilson',
            referenceType: 'faculty',
            referenceId: 6,
            previousValue: JSON.stringify({ department: 'Economics' }),
            newValue: JSON.stringify({ department: 'Economics & Finance' }),
            metadata: null,
            severity: 'info',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000), now),
        },

        // FACULTY_DELETED (3 entries)
        {
            actionType: 'FACULTY_DELETED',
            userId: 'admin-001',
            userName: 'John Admin',
            timestamp: getRandomDate(new Date(now.getTime() - 18 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 16 * 24 * 60 * 60 * 1000)),
            description: 'Faculty deleted: Dr. Thomas White',
            referenceType: 'faculty',
            referenceId: 10,
            previousValue: JSON.stringify({ id: 10, name: 'Dr. Thomas White', email: 'twhite@uni.edu', department: 'Sociology' }),
            newValue: null,
            metadata: JSON.stringify({ reason: 'retirement' }),
            severity: 'warning',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 18 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 16 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'FACULTY_DELETED',
            userId: 'admin-004',
            userName: 'Emily Supervisor',
            timestamp: getRandomDate(new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000)),
            description: 'Faculty deleted: Dr. Patricia Moore',
            referenceType: 'faculty',
            referenceId: 11,
            previousValue: JSON.stringify({ id: 11, name: 'Dr. Patricia Moore', email: 'pmoore@uni.edu', department: 'Art' }),
            newValue: null,
            metadata: JSON.stringify({ reason: 'resignation' }),
            severity: 'warning',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'FACULTY_DELETED',
            userId: 'admin-002',
            userName: 'Sarah Manager',
            timestamp: getRandomDate(new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000)),
            description: 'Faculty deleted: Dr. Richard Garcia',
            referenceType: 'faculty',
            referenceId: 12,
            previousValue: JSON.stringify({ id: 12, name: 'Dr. Richard Garcia', email: 'rgarcia@uni.edu', department: 'Political Science' }),
            newValue: null,
            metadata: JSON.stringify({ reason: 'contract end' }),
            severity: 'warning',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000)),
        },

        // SUBJECT_ADDED (11 entries)
        {
            actionType: 'SUBJECT_ADDED',
            userId: 'admin-003',
            userName: 'Mike Coordinator',
            timestamp: getRandomDate(thirtyDaysAgo, new Date(now.getTime() - 26 * 24 * 60 * 60 * 1000)),
            description: 'Subject added: Advanced Database Systems (CS402)',
            referenceType: 'subject',
            referenceId: 1,
            previousValue: null,
            newValue: JSON.stringify({ id: 1, name: 'Advanced Database Systems', code: 'CS402', credits: 3 }),
            metadata: null,
            severity: 'success',
            isSystemAction: false,
            createdAt: getRandomDate(thirtyDaysAgo, new Date(now.getTime() - 26 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'SUBJECT_ADDED',
            userId: 'admin-001',
            userName: 'John Admin',
            timestamp: getRandomDate(new Date(now.getTime() - 25 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 24 * 24 * 60 * 60 * 1000)),
            description: 'Subject added: Data Structures (CS201)',
            referenceType: 'subject',
            referenceId: 2,
            previousValue: null,
            newValue: JSON.stringify({ id: 2, name: 'Data Structures', code: 'CS201', credits: 4 }),
            metadata: null,
            severity: 'success',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 25 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 24 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'SUBJECT_ADDED',
            userId: 'admin-002',
            userName: 'Sarah Manager',
            timestamp: getRandomDate(new Date(now.getTime() - 23 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 22 * 24 * 60 * 60 * 1000)),
            description: 'Subject added: Calculus II (MATH202)',
            referenceType: 'subject',
            referenceId: 3,
            previousValue: null,
            newValue: JSON.stringify({ id: 3, name: 'Calculus II', code: 'MATH202', credits: 4 }),
            metadata: null,
            severity: 'success',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 23 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 22 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'SUBJECT_ADDED',
            userId: 'admin-005',
            userName: 'David Controller',
            timestamp: getRandomDate(new Date(now.getTime() - 21 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 20 * 24 * 60 * 60 * 1000)),
            description: 'Subject added: Quantum Physics (PHY301)',
            referenceType: 'subject',
            referenceId: 4,
            previousValue: null,
            newValue: JSON.stringify({ id: 4, name: 'Quantum Physics', code: 'PHY301', credits: 3 }),
            metadata: null,
            severity: 'success',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 21 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 20 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'SUBJECT_ADDED',
            userId: 'admin-004',
            userName: 'Emily Supervisor',
            timestamp: getRandomDate(new Date(now.getTime() - 19 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 18 * 24 * 60 * 60 * 1000)),
            description: 'Subject added: Organic Chemistry (CHEM302)',
            referenceType: 'subject',
            referenceId: 5,
            previousValue: null,
            newValue: JSON.stringify({ id: 5, name: 'Organic Chemistry', code: 'CHEM302', credits: 4 }),
            metadata: null,
            severity: 'success',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 19 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 18 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'SUBJECT_ADDED',
            userId: 'admin-003',
            userName: 'Mike Coordinator',
            timestamp: getRandomDate(new Date(now.getTime() - 17 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 16 * 24 * 60 * 60 * 1000)),
            description: 'Subject added: Molecular Biology (BIO401)',
            referenceType: 'subject',
            referenceId: 6,
            previousValue: null,
            newValue: JSON.stringify({ id: 6, name: 'Molecular Biology', code: 'BIO401', credits: 3 }),
            metadata: null,
            severity: 'success',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 17 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 16 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'SUBJECT_ADDED',
            userId: 'admin-001',
            userName: 'John Admin',
            timestamp: getRandomDate(new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 14 * 24 * 60 * 60 * 1000)),
            description: 'Subject added: Microeconomics (ECON201)',
            referenceType: 'subject',
            referenceId: 7,
            previousValue: null,
            newValue: JSON.stringify({ id: 7, name: 'Microeconomics', code: 'ECON201', credits: 3 }),
            metadata: null,
            severity: 'success',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 14 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'SUBJECT_ADDED',
            userId: 'admin-002',
            userName: 'Sarah Manager',
            timestamp: getRandomDate(new Date(now.getTime() - 13 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000)),
            description: 'Subject added: British Literature (ENG303)',
            referenceType: 'subject',
            referenceId: 8,
            previousValue: null,
            newValue: JSON.stringify({ id: 8, name: 'British Literature', code: 'ENG303', credits: 3 }),
            metadata: null,
            severity: 'success',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 13 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'SUBJECT_ADDED',
            userId: 'admin-005',
            userName: 'David Controller',
            timestamp: getRandomDate(new Date(now.getTime() - 11 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000)),
            description: 'Subject added: World History (HIST202)',
            referenceType: 'subject',
            referenceId: 9,
            previousValue: null,
            newValue: JSON.stringify({ id: 9, name: 'World History', code: 'HIST202', credits: 3 }),
            metadata: null,
            severity: 'success',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 11 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'SUBJECT_ADDED',
            userId: 'admin-004',
            userName: 'Emily Supervisor',
            timestamp: getRandomDate(new Date(now.getTime() - 9 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000)),
            description: 'Subject added: Cognitive Psychology (PSY301)',
            referenceType: 'subject',
            referenceId: 10,
            previousValue: null,
            newValue: JSON.stringify({ id: 10, name: 'Cognitive Psychology', code: 'PSY301', credits: 3 }),
            metadata: null,
            severity: 'success',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 9 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'SUBJECT_ADDED',
            userId: 'admin-003',
            userName: 'Mike Coordinator',
            timestamp: getRandomDate(new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000)),
            description: 'Subject added: Algorithms (CS301)',
            referenceType: 'subject',
            referenceId: 11,
            previousValue: null,
            newValue: JSON.stringify({ id: 11, name: 'Algorithms', code: 'CS301', credits: 3 }),
            metadata: null,
            severity: 'success',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000)),
        },

        // SUBJECT_UPDATED (7 entries)
        {
            actionType: 'SUBJECT_UPDATED',
            userId: 'admin-001',
            userName: 'John Admin',
            timestamp: getRandomDate(new Date(now.getTime() - 22 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 20 * 24 * 60 * 60 * 1000)),
            description: 'Subject updated: Data Structures',
            referenceType: 'subject',
            referenceId: 2,
            previousValue: JSON.stringify({ credits: 4 }),
            newValue: JSON.stringify({ credits: 3 }),
            metadata: null,
            severity: 'info',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 22 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 20 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'SUBJECT_UPDATED',
            userId: 'admin-002',
            userName: 'Sarah Manager',
            timestamp: getRandomDate(new Date(now.getTime() - 18 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 16 * 24 * 60 * 60 * 1000)),
            description: 'Subject updated: Advanced Database Systems',
            referenceType: 'subject',
            referenceId: 1,
            previousValue: JSON.stringify({ name: 'Advanced Database Systems' }),
            newValue: JSON.stringify({ name: 'Advanced Database Management Systems' }),
            metadata: null,
            severity: 'info',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 18 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 16 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'SUBJECT_UPDATED',
            userId: 'admin-004',
            userName: 'Emily Supervisor',
            timestamp: getRandomDate(new Date(now.getTime() - 14 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000)),
            description: 'Subject updated: Calculus II',
            referenceType: 'subject',
            referenceId: 3,
            previousValue: JSON.stringify({ code: 'MATH202' }),
            newValue: JSON.stringify({ code: 'MATH2202' }),
            metadata: null,
            severity: 'info',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 14 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'SUBJECT_UPDATED',
            userId: 'admin-003',
            userName: 'Mike Coordinator',
            timestamp: getRandomDate(new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000)),
            description: 'Subject updated: Organic Chemistry',
            referenceType: 'subject',
            referenceId: 5,
            previousValue: JSON.stringify({ credits: 4 }),
            newValue: JSON.stringify({ credits: 3 }),
            metadata: null,
            severity: 'info',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'SUBJECT_UPDATED',
            userId: 'admin-005',
            userName: 'David Controller',
            timestamp: getRandomDate(new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000)),
            description: 'Subject updated: Quantum Physics',
            referenceType: 'subject',
            referenceId: 4,
            previousValue: JSON.stringify({ name: 'Quantum Physics' }),
            newValue: JSON.stringify({ name: 'Quantum Mechanics' }),
            metadata: null,
            severity: 'info',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'SUBJECT_UPDATED',
            userId: 'admin-001',
            userName: 'John Admin',
            timestamp: getRandomDate(new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000)),
            description: 'Subject updated: Molecular Biology',
            referenceType: 'subject',
            referenceId: 6,
            previousValue: JSON.stringify({ code: 'BIO401' }),
            newValue: JSON.stringify({ code: 'BIO4401' }),
            metadata: null,
            severity: 'info',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'SUBJECT_UPDATED',
            userId: 'admin-002',
            userName: 'Sarah Manager',
            timestamp: getRandomDate(new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000), now),
            description: 'Subject updated: Algorithms',
            referenceType: 'subject',
            referenceId: 11,
            previousValue: JSON.stringify({ credits: 3 }),
            newValue: JSON.stringify({ credits: 4 }),
            metadata: null,
            severity: 'info',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000), now),
        },

        // SUBJECT_DELETED (2 entries)
        {
            actionType: 'SUBJECT_DELETED',
            userId: 'admin-004',
            userName: 'Emily Supervisor',
            timestamp: getRandomDate(new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 13 * 24 * 60 * 60 * 1000)),
            description: 'Subject deleted: Introduction to Sociology',
            referenceType: 'subject',
            referenceId: 12,
            previousValue: JSON.stringify({ id: 12, name: 'Introduction to Sociology', code: 'SOC101', credits: 3 }),
            newValue: null,
            metadata: JSON.stringify({ reason: 'course discontinued' }),
            severity: 'warning',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 13 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'SUBJECT_DELETED',
            userId: 'admin-003',
            userName: 'Mike Coordinator',
            timestamp: getRandomDate(new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000)),
            description: 'Subject deleted: Ancient Philosophy',
            referenceType: 'subject',
            referenceId: 13,
            previousValue: JSON.stringify({ id: 13, name: 'Ancient Philosophy', code: 'PHIL301', credits: 3 }),
            newValue: null,
            metadata: JSON.stringify({ reason: 'low enrollment' }),
            severity: 'warning',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000)),
        },

        // CLASSROOM_ADDED (9 entries)
        {
            actionType: 'CLASSROOM_ADDED',
            userId: 'admin-005',
            userName: 'David Controller',
            timestamp: getRandomDate(thirtyDaysAgo, new Date(now.getTime() - 27 * 24 * 60 * 60 * 1000)),
            description: 'Classroom added: Room 101 in Building A',
            referenceType: 'classroom',
            referenceId: 1,
            previousValue: null,
            newValue: JSON.stringify({ id: 1, roomNumber: '101', building: 'Building A', capacity: 30 }),
            metadata: null,
            severity: 'success',
            isSystemAction: false,
            createdAt: getRandomDate(thirtyDaysAgo, new Date(now.getTime() - 27 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'CLASSROOM_ADDED',
            userId: 'admin-001',
            userName: 'John Admin',
            timestamp: getRandomDate(new Date(now.getTime() - 26 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 25 * 24 * 60 * 60 * 1000)),
            description: 'Classroom added: Room 201 in Building B',
            referenceType: 'classroom',
            referenceId: 2,
            previousValue: null,
            newValue: JSON.stringify({ id: 2, roomNumber: '201', building: 'Building B', capacity: 40 }),
            metadata: null,
            severity: 'success',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 26 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 25 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'CLASSROOM_ADDED',
            userId: 'admin-002',
            userName: 'Sarah Manager',
            timestamp: getRandomDate(new Date(now.getTime() - 24 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 23 * 24 * 60 * 60 * 1000)),
            description: 'Classroom added: Lab 301 in Building C',
            referenceType: 'classroom',
            referenceId: 3,
            previousValue: null,
            newValue: JSON.stringify({ id: 3, roomNumber: 'Lab 301', building: 'Building C', capacity: 25 }),
            metadata: null,
            severity: 'success',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 24 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 23 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'CLASSROOM_ADDED',
            userId: 'admin-003',
            userName: 'Mike Coordinator',
            timestamp: getRandomDate(new Date(now.getTime() - 22 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 21 * 24 * 60 * 60 * 1000)),
            description: 'Classroom added: Auditorium 401 in Building D',
            referenceType: 'classroom',
            referenceId: 4,
            previousValue: null,
            newValue: JSON.stringify({ id: 4, roomNumber: 'Auditorium 401', building: 'Building D', capacity: 150 }),
            metadata: null,
            severity: 'success',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 22 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 21 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'CLASSROOM_ADDED',
            userId: 'admin-004',
            userName: 'Emily Supervisor',
            timestamp: getRandomDate(new Date(now.getTime() - 20 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 19 * 24 * 60 * 60 * 1000)),
            description: 'Classroom added: Lab 501 in Building E',
            referenceType: 'classroom',
            referenceId: 5,
            previousValue: null,
            newValue: JSON.stringify({ id: 5, roomNumber: 'Lab 501', building: 'Building E', capacity: 20 }),
            metadata: null,
            severity: 'success',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 20 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 19 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'CLASSROOM_ADDED',
            userId: 'admin-005',
            userName: 'David Controller',
            timestamp: getRandomDate(new Date(now.getTime() - 18 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 17 * 24 * 60 * 60 * 1000)),
            description: 'Classroom added: Room 102 in Building A',
            referenceType: 'classroom',
            referenceId: 6,
            previousValue: null,
            newValue: JSON.stringify({ id: 6, roomNumber: '102', building: 'Building A', capacity: 35 }),
            metadata: null,
            severity: 'success',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 18 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 17 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'CLASSROOM_ADDED',
            userId: 'admin-001',
            userName: 'John Admin',
            timestamp: getRandomDate(new Date(now.getTime() - 16 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000)),
            description: 'Classroom added: Room 202 in Building B',
            referenceType: 'classroom',
            referenceId: 7,
            previousValue: null,
            newValue: JSON.stringify({ id: 7, roomNumber: '202', building: 'Building B', capacity: 45 }),
            metadata: null,
            severity: 'success',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 16 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'CLASSROOM_ADDED',
            userId: 'admin-002',
            userName: 'Sarah Manager',
            timestamp: getRandomDate(new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 11 * 24 * 60 * 60 * 1000)),
            description: 'Classroom added: Seminar Room 601 in Building F',
            referenceType: 'classroom',
            referenceId: 8,
            previousValue: null,
            newValue: JSON.stringify({ id: 8, roomNumber: 'Seminar Room 601', building: 'Building F', capacity: 15 }),
            metadata: null,
            severity: 'success',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 11 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'CLASSROOM_ADDED',
            userId: 'admin-003',
            userName: 'Mike Coordinator',
            timestamp: getRandomDate(new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000)),
            description: 'Classroom added: Lab 302 in Building C',
            referenceType: 'classroom',
            referenceId: 9,
            previousValue: null,
            newValue: JSON.stringify({ id: 9, roomNumber: 'Lab 302', building: 'Building C', capacity: 28 }),
            metadata: null,
            severity: 'success',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000)),
        },

        // CLASSROOM_UPDATED (5 entries)
        {
            actionType: 'CLASSROOM_UPDATED',
            userId: 'admin-004',
            userName: 'Emily Supervisor',
            timestamp: getRandomDate(new Date(now.getTime() - 19 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 17 * 24 * 60 * 60 * 1000)),
            description: 'Classroom updated: Room 101',
            referenceType: 'classroom',
            referenceId: 1,
            previousValue: JSON.stringify({ capacity: 30 }),
            newValue: JSON.stringify({ capacity: 32 }),
            metadata: null,
            severity: 'info',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 19 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 17 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'CLASSROOM_UPDATED',
            userId: 'admin-005',
            userName: 'David Controller',
            timestamp: getRandomDate(new Date(now.getTime() - 14 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000)),
            description: 'Classroom updated: Room 201',
            referenceType: 'classroom',
            referenceId: 2,
            previousValue: JSON.stringify({ capacity: 40 }),
            newValue: JSON.stringify({ capacity: 42 }),
            metadata: null,
            severity: 'info',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 14 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'CLASSROOM_UPDATED',
            userId: 'admin-001',
            userName: 'John Admin',
            timestamp: getRandomDate(new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000)),
            description: 'Classroom updated: Lab 301',
            referenceType: 'classroom',
            referenceId: 3,
            previousValue: JSON.stringify({ building: 'Building C' }),
            newValue: JSON.stringify({ building: 'Building C-Wing 1' }),
            metadata: null,
            severity: 'info',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'CLASSROOM_UPDATED',
            userId: 'admin-002',
            userName: 'Sarah Manager',
            timestamp: getRandomDate(new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000)),
            description: 'Classroom updated: Auditorium 401',
            referenceType: 'classroom',
            referenceId: 4,
            previousValue: JSON.stringify({ capacity: 150 }),
            newValue: JSON.stringify({ capacity: 160 }),
            metadata: null,
            severity: 'info',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'CLASSROOM_UPDATED',
            userId: 'admin-003',
            userName: 'Mike Coordinator',
            timestamp: getRandomDate(new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000), now),
            description: 'Classroom updated: Lab 501',
            referenceType: 'classroom',
            referenceId: 5,
            previousValue: JSON.stringify({ capacity: 20 }),
            newValue: JSON.stringify({ capacity: 22 }),
            metadata: null,
            severity: 'info',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000), now),
        },

        // CLASSROOM_DELETED (2 entries)
        {
            actionType: 'CLASSROOM_DELETED',
            userId: 'admin-004',
            userName: 'Emily Supervisor',
            timestamp: getRandomDate(new Date(now.getTime() - 11 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 9 * 24 * 60 * 60 * 1000)),
            description: 'Classroom deleted: Room 103',
            referenceType: 'classroom',
            referenceId: 10,
            previousValue: JSON.stringify({ id: 10, roomNumber: '103', building: 'Building A', capacity: 30 }),
            newValue: null,
            metadata: JSON.stringify({ reason: 'renovation' }),
            severity: 'warning',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 11 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 9 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'CLASSROOM_DELETED',
            userId: 'admin-005',
            userName: 'David Controller',
            timestamp: getRandomDate(new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000)),
            description: 'Classroom deleted: Seminar Room 602',
            referenceType: 'classroom',
            referenceId: 11,
            previousValue: JSON.stringify({ id: 11, roomNumber: 'Seminar Room 602', building: 'Building F', capacity: 12 }),
            newValue: null,
            metadata: JSON.stringify({ reason: 'structural issues' }),
            severity: 'warning',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000)),
        },

        // TIMETABLE_CREATED (22 entries)
        {
            actionType: 'TIMETABLE_CREATED',
            userId: 'admin-001',
            userName: 'John Admin',
            timestamp: getRandomDate(new Date(now.getTime() - 21 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 20 * 24 * 60 * 60 * 1000)),
            description: 'Class scheduled: Data Structures by Dr. Robert Johnson on Monday at 09:00 in Room 101',
            referenceType: 'timetable',
            referenceId: 1,
            previousValue: null,
            newValue: JSON.stringify({ 
                facultyId: 1, 
                subjectId: 2, 
                classroomId: 1, 
                dayOfWeek: 'Monday', 
                startTime: '09:00', 
                endTime: '10:00',
                semester: 'Spring 2024',
                studentGroup: 'Group A'
            }),
            metadata: null,
            severity: 'success',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 21 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 20 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'TIMETABLE_CREATED',
            userId: 'admin-002',
            userName: 'Sarah Manager',
            timestamp: getRandomDate(new Date(now.getTime() - 20 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 19 * 24 * 60 * 60 * 1000)),
            description: 'Class scheduled: Calculus II by Dr. Emily Davis on Tuesday at 10:00 in Room 201',
            referenceType: 'timetable',
            referenceId: 2,
            previousValue: null,
            newValue: JSON.stringify({ 
                facultyId: 2, 
                subjectId: 3, 
                classroomId: 2, 
                dayOfWeek: 'Tuesday', 
                startTime: '10:00', 
                endTime: '11:00',
                semester: 'Spring 2024',
                studentGroup: 'Group B'
            }),
            metadata: null,
            severity: 'success',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 20 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 19 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'TIMETABLE_CREATED',
            userId: 'admin-003',
            userName: 'Mike Coordinator',
            timestamp: getRandomDate(new Date(now.getTime() - 19 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 18 * 24 * 60 * 60 * 1000)),
            description: 'Class scheduled: Quantum Physics by Dr. Sarah Lee on Wednesday at 14:00 in Lab 301',
            referenceType: 'timetable',
            referenceId: 3,
            previousValue: null,
            newValue: JSON.stringify({ 
                facultyId: 3, 
                subjectId: 4, 
                classroomId: 3, 
                dayOfWeek: 'Wednesday', 
                startTime: '14:00', 
                endTime: '15:00',
                semester: 'Spring 2024',
                studentGroup: 'Group C'
            }),
            metadata: null,
            severity: 'success',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 19 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 18 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'TIMETABLE_CREATED',
            userId: 'admin-004',
            userName: 'Emily Supervisor',
            timestamp: getRandomDate(new Date(now.getTime() - 18 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 17 * 24 * 60 * 60 * 1000)),
            description: 'Class scheduled: Organic Chemistry by Dr. Michael Chen on Thursday at 09:00 in Lab 501',
            referenceType: 'timetable',
            referenceId: 4,
            previousValue: null,
            newValue: JSON.stringify({ 
                facultyId: 4, 
                subjectId: 5, 
                classroomId: 5, 
                dayOfWeek: 'Thursday', 
                startTime: '09:00', 
                endTime: '10:00',
                semester: 'Spring 2024',
                studentGroup: 'Group D'
            }),
            metadata: null,
            severity: 'success',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 18 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 17 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'TIMETABLE_CREATED',
            userId: 'admin-005',
            userName: 'David Controller',
            timestamp: getRandomDate(new Date(now.getTime() - 17 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 16 * 24 * 60 * 60 * 1000)),
            description: 'Class scheduled: Molecular Biology by Dr. Jennifer Brown on Friday at 11:00 in Room 102',
            referenceType: 'timetable',
            referenceId: 5,
            previousValue: null,
            newValue: JSON.stringify({ 
                facultyId: 5, 
                subjectId: 6, 
                classroomId: 6, 
                dayOfWeek: 'Friday', 
                startTime: '11:00', 
                endTime: '12:00',
                semester: 'Spring 2024',
                studentGroup: 'Group E'
            }),
            metadata: null,
            severity: 'success',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 17 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 16 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'TIMETABLE_CREATED',
            userId: 'admin-001',
            userName: 'John Admin',
            timestamp: getRandomDate(new Date(now.getTime() - 16 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000)),
            description: 'Class scheduled: Microeconomics by Dr. David Wilson on Monday at 13:00 in Room 202',
            referenceType: 'timetable',
            referenceId: 6,
            previousValue: null,
            newValue: JSON.stringify({ 
                facultyId: 6, 
                subjectId: 7, 
                classroomId: 7, 
                dayOfWeek: 'Monday', 
                startTime: '13:00', 
                endTime: '14:00',
                semester: 'Spring 2024',
                studentGroup: 'Group F'
            }),
            metadata: null,
            severity: 'success',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 16 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'TIMETABLE_CREATED',
            userId: 'admin-002',
            userName: 'Sarah Manager',
            timestamp: getRandomDate(new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 14 * 24 * 60 * 60 * 1000)),
            description: 'Class scheduled: British Literature by Dr. Amanda Martinez on Tuesday at 15:00 in Seminar Room 601',
            referenceType: 'timetable',
            referenceId: 7,
            previousValue: null,
            newValue: JSON.stringify({ 
                facultyId: 7, 
                subjectId: 8, 
                classroomId: 8, 
                dayOfWeek: 'Tuesday', 
                startTime: '15:00', 
                endTime: '16:00',
                semester: 'Spring 2024',
                studentGroup: 'Group A'
            }),
            metadata: null,
            severity: 'success',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 14 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'TIMETABLE_CREATED',
            userId: 'admin-003',
            userName: 'Mike Coordinator',
            timestamp: getRandomDate(new Date(now.getTime() - 14 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 13 * 24 * 60 * 60 * 1000)),
            description: 'Class scheduled: World History by Dr. James Taylor on Wednesday at 10:00 in Auditorium 401',
            referenceType: 'timetable',
            referenceId: 8,
            previousValue: null,
            newValue: JSON.stringify({ 
                facultyId: 8, 
                subjectId: 9, 
                classroomId: 4, 
                dayOfWeek: 'Wednesday', 
                startTime: '10:00', 
                endTime: '11:00',
                semester: 'Spring 2024',
                studentGroup: 'Group B'
            }),
            metadata: null,
            severity: 'success',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 14 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 13 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'TIMETABLE_CREATED',
            userId: 'admin-004',
            userName: 'Emily Supervisor',
            timestamp: getRandomDate(new Date(now.getTime() - 13 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000)),
            description: 'Class scheduled: Cognitive Psychology by Dr. Lisa Anderson on Thursday at 14:00 in Room 101',
            referenceType: 'timetable',
            referenceId: 9,
            previousValue: null,
            newValue: JSON.stringify({ 
                facultyId: 9, 
                subjectId: 10, 
                classroomId: 1, 
                dayOfWeek: 'Thursday', 
                startTime: '14:00', 
                endTime: '15:00',
                semester: 'Spring 2024',
                studentGroup: 'Group C'
            }),
            metadata: null,
            severity: 'success',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 13 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'TIMETABLE_CREATED',
            userId: 'admin-005',
            userName: 'David Controller',
            timestamp: getRandomDate(new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 11 * 24 * 60 * 60 * 1000)),
            description: 'Class scheduled: Algorithms by Dr. Robert Johnson on Friday at 09:00 in Lab 302',
            referenceType: 'timetable',
            referenceId: 10,
            previousValue: null,
            newValue: JSON.stringify({ 
                facultyId: 1, 
                subjectId: 11, 
                classroomId: 9, 
                dayOfWeek: 'Friday', 
                startTime: '09:00', 
                endTime: '10:00',
                semester: 'Spring 2024',
                studentGroup: 'Group D'
            }),
            metadata: null,
            severity: 'success',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 11 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'TIMETABLE_CREATED',
            userId: 'admin-001',
            userName: 'John Admin',
            timestamp: getRandomDate(new Date(now.getTime() - 11 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000)),
            description: 'Class scheduled: Advanced Database Systems by Dr. Robert Johnson on Monday at 11:00 in Room 201',
            referenceType: 'timetable',
            referenceId: 11,
            previousValue: null,
            newValue: JSON.stringify({ 
                facultyId: 1, 
                subjectId: 1, 
                classroomId: 2, 
                dayOfWeek: 'Monday', 
                startTime: '11:00', 
                endTime: '12:00',
                semester: 'Spring 2024',
                studentGroup: 'Group E'
            }),
            metadata: null,
            severity: 'success',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 11 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'TIMETABLE_CREATED',
            userId: 'admin-002',
            userName: 'Sarah Manager',
            timestamp: getRandomDate(new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 9 * 24 * 60 * 60 * 1000)),
            description: 'Class scheduled: Data Structures by Dr. Emily Davis on Tuesday at 13:00 in Lab 301',
            referenceType: 'timetable',
            referenceId: 12,
            previousValue: null,
            newValue: JSON.stringify({ 
                facultyId: 2, 
                subjectId: 2, 
                classroomId: 3, 
                dayOfWeek: 'Tuesday', 
                startTime: '13:00', 
                endTime: '14:00',
                semester: 'Spring 2024',
                studentGroup: 'Group F'
            }),
            metadata: null,
            severity: 'success',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 9 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'TIMETABLE_CREATED',
            userId: 'admin-003',
            userName: 'Mike Coordinator',
            timestamp: getRandomDate(new Date(now.getTime() - 9 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000)),
            description: 'Class scheduled: Calculus II by Dr. Sarah Lee on Wednesday at 09:00 in Room 102',
            referenceType: 'timetable',
            referenceId: 13,
            previousValue: null,
            newValue: JSON.stringify({ 
                facultyId: 3, 
                subjectId: 3, 
                classroomId: 6, 
                dayOfWeek: 'Wednesday', 
                startTime: '09:00', 
                endTime: '10:00',
                semester: 'Spring 2024',
                studentGroup: 'Group A'
            }),
            metadata: null,
            severity: 'success',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 9 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'TIMETABLE_CREATED',
            userId: 'admin-004',
            userName: 'Emily Supervisor',
            timestamp: getRandomDate(new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000)),
            description: 'Class scheduled: Quantum Physics by Dr. Michael Chen on Thursday at 11:00 in Room 202',
            referenceType: 'timetable',
            referenceId: 14,
            previousValue: null,
            newValue: JSON.stringify({ 
                facultyId: 4, 
                subjectId: 4, 
                classroomId: 7, 
                dayOfWeek: 'Thursday', 
                startTime: '11:00', 
                endTime: '12:00',
                semester: 'Spring 2024',
                studentGroup: 'Group B'
            }),
            metadata: null,
            severity: 'success',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'TIMETABLE_CREATED',
            userId: 'admin-005',
            userName: 'David Controller',
            timestamp: getRandomDate(new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000)),
            description: 'Class scheduled: Organic Chemistry by Dr. Jennifer Brown on Friday at 14:00 in Lab 501',
            referenceType: 'timetable',
            referenceId: 15,
            previousValue: null,
            newValue: JSON.stringify({ 
                facultyId: 5, 
                subjectId: 5, 
                classroomId: 5, 
                dayOfWeek: 'Friday', 
                startTime: '14:00', 
                endTime: '15:00',
                semester: 'Spring 2024',
                studentGroup: 'Group C'
            }),
            metadata: null,
            severity: 'success',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'TIMETABLE_CREATED',
            userId: 'admin-001',
            userName: 'John Admin',
            timestamp: getRandomDate(new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000)),
            description: 'Class scheduled: Molecular Biology by Dr. David Wilson on Monday at 15:00 in Seminar Room 601',
            referenceType: 'timetable',
            referenceId: 16,
            previousValue: null,
            newValue: JSON.stringify({ 
                facultyId: 6, 
                subjectId: 6, 
                classroomId: 8, 
                dayOfWeek: 'Monday', 
                startTime: '15:00', 
                endTime: '16:00',
                semester: 'Spring 2024',
                studentGroup: 'Group D'
            }),
            metadata: null,
            severity: 'success',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'TIMETABLE_CREATED',
            userId: 'admin-002',
            userName: 'Sarah Manager',
            timestamp: getRandomDate(new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000)),
            description: 'Class scheduled: Microeconomics by Dr. Amanda Martinez on Tuesday at 09:00 in Auditorium 401',
            referenceType: 'timetable',
            referenceId: 17,
            previousValue: null,
            newValue: JSON.stringify({ 
                facultyId: 7, 
                subjectId: 7, 
                classroomId: 4, 
                dayOfWeek: 'Tuesday', 
                startTime: '09:00', 
                endTime: '10:00',
                semester: 'Spring 2024',
                studentGroup: 'Group E'
            }),
            metadata: null,
            severity: 'success',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'TIMETABLE_CREATED',
            userId: 'admin-003',
            userName: 'Mike Coordinator',
            timestamp: getRandomDate(new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000)),
            description: 'Class scheduled: British Literature by Dr. James Taylor on Wednesday at 11:00 in Room 101',
            referenceType: 'timetable',
            referenceId: 18,
            previousValue: null,
            newValue: JSON.stringify({ 
                facultyId: 8, 
                subjectId: 8, 
                classroomId: 1, 
                dayOfWeek: 'Wednesday', 
                startTime: '11:00', 
                endTime: '12:00',
                semester: 'Spring 2024',
                studentGroup: 'Group F'
            }),
            metadata: null,
            severity: 'success',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'TIMETABLE_CREATED',
            userId: 'admin-004',
            userName: 'Emily Supervisor',
            timestamp: getRandomDate(new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000)),
            description: 'Class scheduled: World History by Dr. Lisa Anderson on Thursday at 13:00 in Room 201',
            referenceType: 'timetable',
            referenceId: 19,
            previousValue: null,
            newValue: JSON.stringify({ 
                facultyId: 9, 
                subjectId: 9, 
                classroomId: 2, 
                dayOfWeek: 'Thursday', 
                startTime: '13:00', 
                endTime: '14:00',
                semester: 'Spring 2024',
                studentGroup: 'Group A'
            }),
            metadata: null,
            severity: 'success',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'TIMETABLE_CREATED',
            userId: 'admin-005',
            userName: 'David Controller',
            timestamp: getRandomDate(new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000)),
            description: 'Class scheduled: Cognitive Psychology by Dr. Robert Johnson on Friday at 15:00 in Lab 302',
            referenceType: 'timetable',
            referenceId: 20,
            previousValue: null,
            newValue: JSON.stringify({ 
                facultyId: 1, 
                subjectId: 10, 
                classroomId: 9, 
                dayOfWeek: 'Friday', 
                startTime: '15:00', 
                endTime: '16:00',
                semester: 'Spring 2024',
                studentGroup: 'Group B'
            }),
            metadata: null,
            severity: 'success',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'TIMETABLE_CREATED',
            userId: 'admin-001',
            userName: 'John Admin',
            timestamp: getRandomDate(new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000), now),
            description: 'Class scheduled: Algorithms by Dr. Emily Davis on Saturday at 10:00 in Room 102',
            referenceType: 'timetable',
            referenceId: 21,
            previousValue: null,
            newValue: JSON.stringify({ 
                facultyId: 2, 
                subjectId: 11, 
                classroomId: 6, 
                dayOfWeek: 'Saturday', 
                startTime: '10:00', 
                endTime: '11:00',
                semester: 'Spring 2024',
                studentGroup: 'Group C'
            }),
            metadata: null,
            severity: 'success',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000), now),
        },
        {
            actionType: 'TIMETABLE_CREATED',
            userId: null,
            userName: null,
            timestamp: getRandomDate(new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000), now),
            description: 'Class scheduled: Advanced Database Systems by Dr. Sarah Lee on Saturday at 13:00 in Lab 301',
            referenceType: 'timetable',
            referenceId: 22,
            previousValue: null,
            newValue: JSON.stringify({ 
                facultyId: 3, 
                subjectId: 1, 
                classroomId: 3, 
                dayOfWeek: 'Saturday', 
                startTime: '13:00', 
                endTime: '14:00',
                semester: 'Spring 2024',
                studentGroup: 'Group D'
            }),
            metadata: JSON.stringify({ automated: true, trigger: 'schedule_optimization' }),
            severity: 'success',
            isSystemAction: true,
            createdAt: getRandomDate(new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000), now),
        },

        // TIMETABLE_MODIFIED (9 entries)
        {
            actionType: 'TIMETABLE_MODIFIED',
            userId: 'admin-002',
            userName: 'Sarah Manager',
            timestamp: getRandomDate(new Date(now.getTime() - 14 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 13 * 24 * 60 * 60 * 1000)),
            description: 'Class modified: Data Structures on Monday',
            referenceType: 'timetable',
            referenceId: 1,
            previousValue: JSON.stringify({ startTime: '09:00', endTime: '10:00', classroomId: 1 }),
            newValue: JSON.stringify({ startTime: '10:00', endTime: '11:00', classroomId: 1 }),
            metadata: null,
            severity: 'info',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 14 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 13 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'TIMETABLE_MODIFIED',
            userId: 'admin-003',
            userName: 'Mike Coordinator',
            timestamp: getRandomDate(new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 11 * 24 * 60 * 60 * 1000)),
            description: 'Class modified: Calculus II on Tuesday',
            referenceType: 'timetable',
            referenceId: 2,
            previousValue: JSON.stringify({ classroomId: 2 }),
            newValue: JSON.stringify({ classroomId: 7 }),
            metadata: null,
            severity: 'info',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 11 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'TIMETABLE_MODIFIED',
            userId: 'admin-004',
            userName: 'Emily Supervisor',
            timestamp: getRandomDate(new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 9 * 24 * 60 * 60 * 1000)),
            description: 'Class modified: Quantum Physics on Wednesday',
            referenceType: 'timetable',
            referenceId: 3,
            previousValue: JSON.stringify({ startTime: '14:00', endTime: '15:00' }),
            newValue: JSON.stringify({ startTime: '15:00', endTime: '16:00' }),
            metadata: null,
            severity: 'info',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 9 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'TIMETABLE_MODIFIED',
            userId: 'admin-005',
            userName: 'David Controller',
            timestamp: getRandomDate(new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000)),
            description: 'Class modified: Organic Chemistry on Thursday',
            referenceType: 'timetable',
            referenceId: 4,
            previousValue: JSON.stringify({ facultyId: 4 }),
            newValue: JSON.stringify({ facultyId: 5 }),
            metadata: null,
            severity: 'info',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'TIMETABLE_MODIFIED',
            userId: 'admin-001',
            userName: 'John Admin',
            timestamp: getRandomDate(new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000)),
            description: 'Class modified: Molecular Biology on Friday',
            referenceType: 'timetable',
            referenceId: 5,
            previousValue: JSON.stringify({ startTime: '11:00', endTime: '12:00', classroomId: 6 }),
            newValue: JSON.stringify({ startTime: '13:00', endTime: '14:00', classroomId: 2 }),
            metadata: null,
            severity: 'info',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'TIMETABLE_MODIFIED',
            userId: 'admin-002',
            userName: 'Sarah Manager',
            timestamp: getRandomDate(new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000)),
            description: 'Class modified: Microeconomics on Monday',
            referenceType: 'timetable',
            referenceId: 6,
            previousValue: JSON.stringify({ dayOfWeek: 'Monday' }),
            newValue: JSON.stringify({ dayOfWeek: 'Tuesday' }),
            metadata: null,
            severity: 'info',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'TIMETABLE_MODIFIED',
            userId: 'admin-003',
            userName: 'Mike Coordinator',
            timestamp: getRandomDate(new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000)),
            description: 'Class modified: British Literature on Tuesday',
            referenceType: 'timetable',
            referenceId: 7,
            previousValue: JSON.stringify({ classroomId: 8 }),
            newValue: JSON.stringify({ classroomId: 4 }),
            metadata: null,
            severity: 'info',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'TIMETABLE_MODIFIED',
            userId: 'admin-004',
            userName: 'Emily Supervisor',
            timestamp: getRandomDate(new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000)),
            description: 'Class modified: World History on Wednesday',
            referenceType: 'timetable',
            referenceId: 8,
            previousValue: JSON.stringify({ startTime: '10:00', endTime: '11:00' }),
            newValue: JSON.stringify({ startTime: '11:00', endTime: '12:00' }),
            metadata: null,
            severity: 'info',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'TIMETABLE_MODIFIED',
            userId: null,
            userName: null,
            timestamp: getRandomDate(new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000), now),
            description: 'Class modified: Cognitive Psychology on Thursday',
            referenceType: 'timetable',
            referenceId: 9,
            previousValue: JSON.stringify({ studentGroup: 'Group C' }),
            newValue: JSON.stringify({ studentGroup: 'Group D' }),
            metadata: JSON.stringify({ automated: true, trigger: 'group_rebalancing' }),
            severity: 'info',
            isSystemAction: true,
            createdAt: getRandomDate(new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000), now),
        },

        // TIMETABLE_DELETED (6 entries)
        {
            actionType: 'TIMETABLE_DELETED',
            userId: 'admin-005',
            userName: 'David Controller',
            timestamp: getRandomDate(new Date(now.getTime() - 13 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000)),
            description: 'Class removed: Algorithms on Friday at 11:00',
            referenceType: 'timetable',
            referenceId: 23,
            previousValue: JSON.stringify({ 
                facultyId: 1, 
                subjectId: 11, 
                classroomId: 9, 
                dayOfWeek: 'Friday', 
                startTime: '11:00', 
                endTime: '12:00'
            }),
            newValue: null,
            metadata: JSON.stringify({ reason: 'faculty unavailable' }),
            severity: 'warning',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 13 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'TIMETABLE_DELETED',
            userId: 'admin-001',
            userName: 'John Admin',
            timestamp: getRandomDate(new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 9 * 24 * 60 * 60 * 1000)),
            description: 'Class removed: Data Structures on Wednesday at 14:00',
            referenceType: 'timetable',
            referenceId: 24,
            previousValue: JSON.stringify({ 
                facultyId: 2, 
                subjectId: 2, 
                classroomId: 3, 
                dayOfWeek: 'Wednesday', 
                startTime: '14:00', 
                endTime: '15:00'
            }),
            newValue: null,
            metadata: JSON.stringify({ reason: 'classroom maintenance' }),
            severity: 'warning',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 9 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'TIMETABLE_DELETED',
            userId: 'admin-002',
            userName: 'Sarah Manager',
            timestamp: getRandomDate(new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000)),
            description: 'Class removed: Calculus II on Thursday at 13:00',
            referenceType: 'timetable',
            referenceId: 25,
            previousValue: JSON.stringify({ 
                facultyId: 2, 
                subjectId: 3, 
                classroomId: 7, 
                dayOfWeek: 'Thursday', 
                startTime: '13:00', 
                endTime: '14:00'
            }),
            newValue: null,
            metadata: JSON.stringify({ reason: 'holiday schedule' }),
            severity: 'warning',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'TIMETABLE_DELETED',
            userId: 'admin-003',
            userName: 'Mike Coordinator',
            timestamp: getRandomDate(new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000)),
            description: 'Class removed: Quantum Physics on Monday at 15:00',
            referenceType: 'timetable',
            referenceId: 26,
            previousValue: JSON.stringify({ 
                facultyId: 3, 
                subjectId: 4, 
                classroomId: 3, 
                dayOfWeek: 'Monday', 
                startTime: '15:00', 
                endTime: '16:00'
            }),
            newValue: null,
            metadata: JSON.stringify({ reason: 'low student attendance' }),
            severity: 'warning',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'TIMETABLE_DELETED',
            userId: 'admin-004',
            userName: 'Emily Supervisor',
            timestamp: getRandomDate(new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000)),
            description: 'Class removed: Organic Chemistry on Tuesday at 11:00',
            referenceType: 'timetable',
            referenceId: 27,
            previousValue: JSON.stringify({ 
                facultyId: 5, 
                subjectId: 5, 
                classroomId: 5, 
                dayOfWeek: 'Tuesday', 
                startTime: '11:00', 
                endTime: '12:00'
            }),
            newValue: null,
            metadata: JSON.stringify({ reason: 'rescheduling' }),
            severity: 'warning',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'TIMETABLE_DELETED',
            userId: null,
            userName: null,
            timestamp: getRandomDate(new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000), now),
            description: 'Class removed: Molecular Biology on Saturday at 09:00',
            referenceType: 'timetable',
            referenceId: 28,
            previousValue: JSON.stringify({ 
                facultyId: 6, 
                subjectId: 6, 
                classroomId: 6, 
                dayOfWeek: 'Saturday', 
                startTime: '09:00', 
                endTime: '10:00'
            }),
            newValue: null,
            metadata: JSON.stringify({ automated: true, trigger: 'weekend_optimization' }),
            severity: 'warning',
            isSystemAction: true,
            createdAt: getRandomDate(new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000), now),
        },

        // CONFLICT_DETECTED (10 entries)
        {
            actionType: 'CONFLICT_DETECTED',
            userId: 'admin-001',
            userName: 'John Admin',
            timestamp: getRandomDate(new Date(now.getTime() - 20 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 19 * 24 * 60 * 60 * 1000)),
            description: 'Faculty conflict detected: Dr. Robert Johnson already has a class on Monday from 09:00 to 10:00',
            referenceType: 'faculty',
            referenceId: 1,
            previousValue: null,
            newValue: null,
            metadata: JSON.stringify({ 
                conflictType: 'faculty', 
                day: 'Monday', 
                time: '09:00-10:00', 
                reason: 'double booking',
                conflictingClassId: 1
            }),
            severity: 'warning',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 20 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 19 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'CONFLICT_DETECTED',
            userId: 'admin-002',
            userName: 'Sarah Manager',
            timestamp: getRandomDate(new Date(now.getTime() - 18 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 17 * 24 * 60 * 60 * 1000)),
            description: 'Classroom conflict detected: Room 201 is already booked on Tuesday from 10:00 to 11:00',
            referenceType: 'classroom',
            referenceId: 2,
            previousValue: null,
            newValue: null,
            metadata: JSON.stringify({ 
                conflictType: 'classroom', 
                day: 'Tuesday', 
                time: '10:00-11:00', 
                reason: 'room already occupied',
                conflictingClassId: 2
            }),
            severity: 'warning',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 18 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 17 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'CONFLICT_DETECTED',
            userId: 'admin-003',
            userName: 'Mike Coordinator',
            timestamp: getRandomDate(new Date(now.getTime() - 16 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000)),
            description: 'Student group conflict detected: Group A already has a class on Wednesday from 14:00 to 15:00',
            referenceType: 'timetable',
            referenceId: 3,
            previousValue: null,
            newValue: null,
            metadata: JSON.stringify({ 
                conflictType: 'student_group', 
                day: 'Wednesday', 
                time: '14:00-15:00', 
                reason: 'group already scheduled',
                studentGroup: 'Group A',
                conflictingClassId: 3
            }),
            severity: 'warning',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 16 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'CONFLICT_DETECTED',
            userId: 'admin-004',
            userName: 'Emily Supervisor',
            timestamp: getRandomDate(new Date(now.getTime() - 14 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 13 * 24 * 60 * 60 * 1000)),
            description: 'Faculty conflict detected: Dr. Emily Davis already has a class on Thursday from 09:00 to 10:00',
            referenceType: 'faculty',
            referenceId: 2,
            previousValue: null,
            newValue: null,
            metadata: JSON.stringify({ 
                conflictType: 'faculty', 
                day: 'Thursday', 
                time: '09:00-10:00', 
                reason: 'double booking',
                conflictingClassId: 4
            }),
            severity: 'warning',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 14 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 13 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'CONFLICT_DETECTED',
            userId: 'admin-005',
            userName: 'David Controller',
            timestamp: getRandomDate(new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 11 * 24 * 60 * 60 * 1000)),
            description: 'Classroom conflict detected: Lab 501 is already booked on Friday from 11:00 to 12:00',
            referenceType: 'classroom',
            referenceId: 5,
            previousValue: null,
            newValue: null,
            metadata: JSON.stringify({ 
                conflictType: 'classroom', 
                day: 'Friday', 
                time: '11:00-12:00', 
                reason: 'room already occupied',
                conflictingClassId: 5
            }),
            severity: 'warning',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 11 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'CONFLICT_DETECTED',
            userId: 'admin-001',
            userName: 'John Admin',
            timestamp: getRandomDate(new Date(now.getTime() - 9 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000)),
            description: 'Student group conflict detected: Group B already has a class on Monday from 13:00 to 14:00',
            referenceType: 'timetable',
            referenceId: 6,
            previousValue: null,
            newValue: null,
            metadata: JSON.stringify({ 
                conflictType: 'student_group', 
                day: 'Monday', 
                time: '13:00-14:00', 
                reason: 'group already scheduled',
                studentGroup: 'Group B',
                conflictingClassId: 6
            }),
            severity: 'warning',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 9 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'CONFLICT_DETECTED',
            userId: 'admin-002',
            userName: 'Sarah Manager',
            timestamp: getRandomDate(new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000)),
            description: 'Faculty conflict detected: Dr. Sarah Lee already has a class on Tuesday from 15:00 to 16:00',
            referenceType: 'faculty',
            referenceId: 3,
            previousValue: null,
            newValue: null,
            metadata: JSON.stringify({ 
                conflictType: 'faculty', 
                day: 'Tuesday', 
                time: '15:00-16:00', 
                reason: 'double booking',
                conflictingClassId: 7
            }),
            severity: 'warning',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'CONFLICT_DETECTED',
            userId: 'admin-003',
            userName: 'Mike Coordinator',
            timestamp: getRandomDate(new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000)),
            description: 'Classroom conflict detected: Auditorium 401 is already booked on Wednesday from 10:00 to 11:00',
            referenceType: 'classroom',
            referenceId: 4,
            previousValue: null,
            newValue: null,
            metadata: JSON.stringify({ 
                conflictType: 'classroom', 
                day: 'Wednesday', 
                time: '10:00-11:00', 
                reason: 'room already occupied',
                conflictingClassId: 8
            }),
            severity: 'warning',
            isSystemAction: false,
            createdAt: getRandomDate(new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'CONFLICT_DETECTED',
            userId: null,
            userName: null,
            timestamp: getRandomDate(new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000)),
            description: 'Student group conflict detected: Group C already has a class on Thursday from 14:00 to 15:00',
            referenceType: 'timetable',
            referenceId: 9,
            previousValue: null,
            newValue: null,
            metadata: JSON.stringify({ 
                conflictType: 'student_group', 
                day: 'Thursday', 
                time: '14:00-15:00', 
                reason: 'group already scheduled',
                studentGroup: 'Group C',
                conflictingClassId: 9,
                automated: true,
                trigger: 'schedule_validation'
            }),
            severity: 'error',
            isSystemAction: true,
            createdAt: getRandomDate(new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000), new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000)),
        },
        {
            actionType: 'CONFLICT_DETECTED',
            userId: null,
            userName: null,
            timestamp: getRandomDate(new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000), now),
            description: 'Faculty conflict detected: Dr. Michael Chen already has a class on Friday from 09:00 to 10:00',
            referenceType: 'faculty',
            referenceId: 4,
            previousValue: null,
            newValue: null,
            metadata: JSON.stringify({ 
                conflictType: 'faculty', 
                day: 'Friday', 
                time: '09:00-10:00', 
                reason: 'double booking',
                conflictingClassId: 10,
                automated: true,
                trigger: 'automated_scheduling'
            }),
            severity: 'error',
            isSystemAction: true,
            createdAt: getRandomDate(new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000), now),
        },
    ];

    // Sort by timestamp to ensure chronological order
    sampleLogs.sort((a, b) => new Date(a.timestamp).getTime() - new Date(b.timestamp).getTime());

    await db.insert(activityLogs).values(sampleLogs);
    
    console.log('✅ Activity logs seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});