import { db } from '@/db';
import { notifications } from '@/db/schema';

async function main() {
    const sampleNotifications = [
        // INFO NOTIFICATIONS (5)
        {
            title: 'Faculty Meeting Scheduled',
            message: 'Department meeting scheduled for Monday, January 22 at 2:00 PM in Conference Room A. Attendance is mandatory.',
            notificationType: 'info',
            severity: 'low',
            targetUserType: 'faculty',
            targetUserId: 1,
            referenceType: null,
            referenceId: null,
            metadata: '{"location":"Conference Room A","date":"2024-01-22","time":"14:00"}',
            isRead: false,
            isSent: true,
            sentAt: new Date('2024-01-18T09:30:00').toISOString(),
            readAt: null,
            createdAt: new Date('2024-01-18T09:30:00').toISOString(),
        },
        {
            title: 'New Academic Calendar Released',
            message: 'The academic calendar for Spring 2024 semester has been published. Please review important dates and deadlines.',
            notificationType: 'info',
            severity: 'medium',
            targetUserType: 'all',
            targetUserId: null,
            referenceType: null,
            referenceId: null,
            metadata: '{"semester":"Spring 2024","publishDate":"2024-01-15"}',
            isRead: true,
            isSent: true,
            sentAt: new Date('2024-01-15T10:00:00').toISOString(),
            readAt: new Date('2024-01-15T15:30:00').toISOString(),
            createdAt: new Date('2024-01-15T10:00:00').toISOString(),
        },
        {
            title: 'System Maintenance Notice',
            message: 'Scheduled system maintenance on Saturday, January 20 from 11:00 PM to 2:00 AM. Timetable system will be unavailable.',
            notificationType: 'info',
            severity: 'medium',
            targetUserType: 'all',
            targetUserId: null,
            referenceType: null,
            referenceId: null,
            metadata: '{"maintenanceStart":"2024-01-20T23:00:00","maintenanceEnd":"2024-01-21T02:00:00"}',
            isRead: false,
            isSent: true,
            sentAt: new Date('2024-01-17T11:00:00').toISOString(),
            readAt: null,
            createdAt: new Date('2024-01-17T11:00:00').toISOString(),
        },
        {
            title: 'New Course Materials Available',
            message: 'Updated course materials for Data Structures (CS201) have been uploaded to the system.',
            notificationType: 'info',
            severity: 'low',
            targetUserType: 'faculty',
            targetUserId: 3,
            referenceType: 'timetable',
            referenceId: 5,
            metadata: '{"courseCode":"CS201","uploadDate":"2024-01-19"}',
            isRead: true,
            isSent: true,
            sentAt: new Date('2024-01-19T14:15:00').toISOString(),
            readAt: new Date('2024-01-20T09:00:00').toISOString(),
            createdAt: new Date('2024-01-19T14:15:00').toISOString(),
        },
        {
            title: 'Staff Training Session Announced',
            message: 'Online training session on new timetable management features scheduled for January 25 at 3:00 PM.',
            notificationType: 'info',
            severity: 'low',
            targetUserType: 'admin',
            targetUserId: 1,
            referenceType: null,
            referenceId: null,
            metadata: '{"trainingDate":"2024-01-25","time":"15:00","platform":"Zoom"}',
            isRead: false,
            isSent: true,
            sentAt: new Date('2024-01-16T10:30:00').toISOString(),
            readAt: null,
            createdAt: new Date('2024-01-16T10:30:00').toISOString(),
        },

        // WARNING NOTIFICATIONS (5)
        {
            title: 'Workload Exceeds Recommended Hours',
            message: 'Dr. Sarah Williams teaching hours (25 hrs) exceed recommended limit of 20 hours per week. Please review schedule.',
            notificationType: 'warning',
            severity: 'high',
            targetUserType: 'admin',
            targetUserId: 2,
            referenceType: 'workload',
            referenceId: 2,
            metadata: '{"totalHours":25,"recommended":20,"exceeded":5,"facultyName":"Dr. Sarah Williams"}',
            isRead: false,
            isSent: true,
            sentAt: new Date('2024-01-20T08:45:00').toISOString(),
            readAt: null,
            createdAt: new Date('2024-01-20T08:45:00').toISOString(),
        },
        {
            title: 'Deadline Approaching: Submit Attendance',
            message: 'Attendance submission deadline is January 24. Please submit attendance records for all classes.',
            notificationType: 'warning',
            severity: 'medium',
            targetUserType: 'faculty',
            targetUserId: 4,
            referenceType: null,
            referenceId: null,
            metadata: '{"deadline":"2024-01-24","daysRemaining":4}',
            isRead: false,
            isSent: true,
            sentAt: new Date('2024-01-20T09:00:00').toISOString(),
            readAt: null,
            createdAt: new Date('2024-01-20T09:00:00').toISOString(),
        },
        {
            title: 'Room Capacity Warning',
            message: 'Classroom B-305 assigned student group exceeds room capacity (50 students for 45 capacity room).',
            notificationType: 'warning',
            severity: 'high',
            targetUserType: 'admin',
            targetUserId: 1,
            referenceType: 'timetable',
            referenceId: 12,
            metadata: '{"roomNumber":"B-305","capacity":45,"assigned":50,"exceeded":5}',
            isRead: true,
            isSent: true,
            sentAt: new Date('2024-01-19T11:20:00').toISOString(),
            readAt: new Date('2024-01-19T13:45:00').toISOString(),
            createdAt: new Date('2024-01-19T11:20:00').toISOString(),
        },
        {
            title: 'Incomplete Schedule Submission',
            message: 'Your weekly schedule submission is incomplete. Missing entries for Tuesday and Thursday.',
            notificationType: 'warning',
            severity: 'medium',
            targetUserType: 'faculty',
            targetUserId: 5,
            referenceType: 'schedule_change',
            referenceId: 3,
            metadata: '{"missingDays":["Tuesday","Thursday"],"submissionDeadline":"2024-01-22"}',
            isRead: false,
            isSent: true,
            sentAt: new Date('2024-01-18T15:30:00').toISOString(),
            readAt: null,
            createdAt: new Date('2024-01-18T15:30:00').toISOString(),
        },
        {
            title: 'Examination Paper Submission Pending',
            message: 'Question paper for mid-term examination due in 3 days. Please submit to examination office.',
            notificationType: 'warning',
            severity: 'high',
            targetUserType: 'faculty',
            targetUserId: 2,
            referenceType: 'exam_duty',
            referenceId: 8,
            metadata: '{"examDate":"2024-01-27","daysRemaining":3,"courseCode":"MATH301"}',
            isRead: false,
            isSent: true,
            sentAt: new Date('2024-01-21T10:00:00').toISOString(),
            readAt: null,
            createdAt: new Date('2024-01-21T10:00:00').toISOString(),
        },

        // CONFLICT NOTIFICATIONS (4)
        {
            title: 'Schedule Conflict Detected',
            message: 'Dr. John Smith assigned to two classes at same time: Monday 10:00 AM in rooms A-201 and B-303.',
            notificationType: 'conflict',
            severity: 'critical',
            targetUserType: 'admin',
            targetUserId: 2,
            referenceType: 'timetable',
            referenceId: 7,
            metadata: '{"conflictType":"faculty","time":"10:00","day":"Monday","rooms":["A-201","B-303"],"facultyName":"Dr. John Smith"}',
            isRead: false,
            isSent: true,
            sentAt: new Date('2024-01-21T08:30:00').toISOString(),
            readAt: null,
            createdAt: new Date('2024-01-21T08:30:00').toISOString(),
        },
        {
            title: 'Room Double-Booked',
            message: 'Classroom C-105 scheduled for two different classes on Wednesday at 2:00 PM. Immediate resolution required.',
            notificationType: 'conflict',
            severity: 'critical',
            targetUserType: 'admin',
            targetUserId: 3,
            referenceType: 'timetable',
            referenceId: 15,
            metadata: '{"conflictType":"room","time":"14:00","day":"Wednesday","roomNumber":"C-105","classes":["CS101","MATH201"]}',
            isRead: true,
            isSent: true,
            sentAt: new Date('2024-01-20T13:15:00').toISOString(),
            readAt: new Date('2024-01-20T14:00:00').toISOString(),
            createdAt: new Date('2024-01-20T13:15:00').toISOString(),
        },
        {
            title: 'Faculty Assigned Multiple Classes',
            message: 'Prof. Emily Davis has three consecutive classes scheduled on Friday without break. Consider rescheduling.',
            notificationType: 'conflict',
            severity: 'high',
            targetUserType: 'admin',
            targetUserId: 1,
            referenceType: 'workload',
            referenceId: 4,
            metadata: '{"conflictType":"faculty","day":"Friday","consecutiveClasses":3,"facultyName":"Prof. Emily Davis","startTime":"09:00","endTime":"12:00"}',
            isRead: false,
            isSent: true,
            sentAt: new Date('2024-01-19T16:45:00').toISOString(),
            readAt: null,
            createdAt: new Date('2024-01-19T16:45:00').toISOString(),
        },
        {
            title: 'Time Slot Overlap',
            message: 'Student group CSE-3A has overlapping classes: Database Systems and Web Development both scheduled Tuesday 11:00 AM.',
            notificationType: 'conflict',
            severity: 'critical',
            targetUserType: 'admin',
            targetUserId: 2,
            referenceType: 'timetable',
            referenceId: 18,
            metadata: '{"conflictType":"time","time":"11:00","day":"Tuesday","studentGroup":"CSE-3A","courses":["Database Systems","Web Development"]}',
            isRead: false,
            isSent: true,
            sentAt: new Date('2024-01-21T09:15:00').toISOString(),
            readAt: null,
            createdAt: new Date('2024-01-21T09:15:00').toISOString(),
        },

        // APPROVAL REQUIRED NOTIFICATIONS (4)
        {
            title: 'Schedule Change Requires Approval',
            message: 'Dr. Michael Brown requested to change class timing from 10:00 AM to 2:00 PM on Mondays. Awaiting your approval.',
            notificationType: 'approval_required',
            severity: 'medium',
            targetUserType: 'admin',
            targetUserId: 1,
            referenceType: 'schedule_change',
            referenceId: 6,
            metadata: '{"oldTime":"10:00","newTime":"14:00","reason":"personal commitment","requestedBy":"Dr. Michael Brown","requestDate":"2024-01-19"}',
            isRead: true,
            isSent: true,
            sentAt: new Date('2024-01-19T10:30:00').toISOString(),
            readAt: new Date('2024-01-19T11:15:00').toISOString(),
            createdAt: new Date('2024-01-19T10:30:00').toISOString(),
        },
        {
            title: 'Room Booking Pending',
            message: 'Seminar Hall booking request for guest lecture on January 26, 3:00 PM - 5:00 PM requires approval.',
            notificationType: 'approval_required',
            severity: 'medium',
            targetUserType: 'admin',
            targetUserId: 3,
            referenceType: null,
            referenceId: null,
            metadata: '{"roomType":"Seminar Hall","date":"2024-01-26","time":"15:00-17:00","requestedBy":"Dr. Lisa Anderson","purpose":"guest lecture","requestDate":"2024-01-18"}',
            isRead: false,
            isSent: true,
            sentAt: new Date('2024-01-18T14:20:00').toISOString(),
            readAt: null,
            createdAt: new Date('2024-01-18T14:20:00').toISOString(),
        },
        {
            title: 'Leave Request Pending',
            message: 'Faculty leave application from Dr. Robert Taylor for January 24-26. Substitute arrangement needs approval.',
            notificationType: 'approval_required',
            severity: 'high',
            targetUserType: 'admin',
            targetUserId: 2,
            referenceType: 'schedule_change',
            referenceId: 9,
            metadata: '{"requestedBy":"Dr. Robert Taylor","leaveStart":"2024-01-24","leaveEnd":"2024-01-26","reason":"medical","substituteRequired":true,"requestDate":"2024-01-17"}',
            isRead: false,
            isSent: true,
            sentAt: new Date('2024-01-17T09:45:00').toISOString(),
            readAt: null,
            createdAt: new Date('2024-01-17T09:45:00').toISOString(),
        },
        {
            title: 'Extra Class Request',
            message: 'Request to schedule makeup class for missed session on January 23, Saturday 10:00 AM. Awaiting approval.',
            notificationType: 'approval_required',
            severity: 'medium',
            targetUserType: 'admin',
            targetUserId: 1,
            referenceType: 'timetable',
            referenceId: 3,
            metadata: '{"requestedBy":"Prof. Nancy White","date":"2024-01-23","time":"10:00","reason":"holiday compensation","courseCode":"PHY202","requestDate":"2024-01-20"}',
            isRead: false,
            isSent: true,
            sentAt: new Date('2024-01-20T11:00:00').toISOString(),
            readAt: null,
            createdAt: new Date('2024-01-20T11:00:00').toISOString(),
        },

        // SYSTEM NOTIFICATIONS (4)
        {
            title: 'Auto-Generated Timetable Ready',
            message: 'System has generated optimized timetable for Spring 2024 semester. Review and approve to publish.',
            notificationType: 'system',
            severity: 'low',
            targetUserType: 'admin',
            targetUserId: 1,
            referenceType: 'timetable',
            referenceId: 1,
            metadata: '{"generatedAt":"2024-01-16T03:00:00","semester":"Spring 2024","totalClasses":156,"conflicts":0}',
            isRead: true,
            isSent: true,
            sentAt: new Date('2024-01-16T08:00:00').toISOString(),
            readAt: new Date('2024-01-16T09:30:00').toISOString(),
            createdAt: new Date('2024-01-16T08:00:00').toISOString(),
        },
        {
            title: 'Backup Completed',
            message: 'Daily database backup completed successfully at 2:00 AM. All data secured.',
            notificationType: 'system',
            severity: 'low',
            targetUserType: 'admin',
            targetUserId: 2,
            referenceType: null,
            referenceId: null,
            metadata: '{"backupTime":"2024-01-21T02:00:00","size":"2.4GB","status":"success","nextBackup":"2024-01-22T02:00:00"}',
            isRead: true,
            isSent: true,
            sentAt: new Date('2024-01-21T08:00:00').toISOString(),
            readAt: new Date('2024-01-21T08:15:00').toISOString(),
            createdAt: new Date('2024-01-21T08:00:00').toISOString(),
        },
        {
            title: 'Report Generated',
            message: 'Weekly workload distribution report for all faculty members has been generated and is ready for download.',
            notificationType: 'system',
            severity: 'low',
            targetUserType: 'admin',
            targetUserId: 3,
            referenceType: 'workload',
            referenceId: 1,
            metadata: '{"reportType":"workload_distribution","period":"Week 3 Jan 2024","format":"PDF","size":"1.2MB","generatedAt":"2024-01-20T18:00:00"}',
            isRead: false,
            isSent: true,
            sentAt: new Date('2024-01-20T18:05:00').toISOString(),
            readAt: null,
            createdAt: new Date('2024-01-20T18:05:00').toISOString(),
        },
        {
            title: 'Automated Reminder Sent',
            message: 'System sent automated attendance reminder to 45 faculty members for pending submissions.',
            notificationType: 'system',
            severity: 'low',
            targetUserType: 'admin',
            targetUserId: 1,
            referenceType: null,
            referenceId: null,
            metadata: '{"reminderType":"attendance","recipientCount":45,"sentAt":"2024-01-19T09:00:00","deliveryStatus":"success"}',
            isRead: true,
            isSent: true,
            sentAt: new Date('2024-01-19T09:05:00').toISOString(),
            readAt: new Date('2024-01-19T10:00:00').toISOString(),
            createdAt: new Date('2024-01-19T09:05:00').toISOString(),
        },

        // ADDITIONAL MIXED NOTIFICATIONS (3)
        {
            title: 'Holiday Announcement',
            message: 'Republic Day holiday on January 26. All classes cancelled. Regular schedule resumes January 27.',
            notificationType: 'info',
            severity: 'medium',
            targetUserType: 'all',
            targetUserId: null,
            referenceType: 'holiday',
            referenceId: null,
            metadata: '{"holidayName":"Republic Day","date":"2024-01-26","resumeDate":"2024-01-27"}',
            isRead: false,
            isSent: true,
            sentAt: new Date('2024-01-15T12:00:00').toISOString(),
            readAt: null,
            createdAt: new Date('2024-01-15T12:00:00').toISOString(),
        },
        {
            title: 'Exam Duty Assignment',
            message: 'You have been assigned invigilation duty for mid-term examinations on January 28-30. Check schedule details.',
            notificationType: 'info',
            severity: 'high',
            targetUserType: 'faculty',
            targetUserId: 3,
            referenceType: 'exam_duty',
            referenceId: 12,
            metadata: '{"examPeriod":"2024-01-28 to 2024-01-30","shifts":3,"roomAssignments":["A-301","B-205","C-107"]}',
            isRead: false,
            isSent: true,
            sentAt: new Date('2024-01-18T13:30:00').toISOString(),
            readAt: null,
            createdAt: new Date('2024-01-18T13:30:00').toISOString(),
        },
        {
            title: 'Salary Credit Notification',
            message: 'Monthly salary for January 2024 has been credited to your account. Download salary slip from portal.',
            notificationType: 'info',
            severity: 'low',
            targetUserType: 'faculty',
            targetUserId: 4,
            referenceType: 'salary',
            referenceId: 1,
            metadata: '{"month":"January 2024","creditDate":"2024-01-20","slipAvailable":true}',
            isRead: true,
            isSent: true,
            sentAt: new Date('2024-01-20T10:00:00').toISOString(),
            readAt: new Date('2024-01-20T12:30:00').toISOString(),
            createdAt: new Date('2024-01-20T10:00:00').toISOString(),
        },
        {
            title: 'Library Resources Updated',
            message: 'New digital resources and e-books added to library database. Access credentials available on staff portal.',
            notificationType: 'info',
            severity: 'low',
            targetUserType: 'all',
            targetUserId: null,
            referenceType: null,
            referenceId: null,
            metadata: '{"resourceCount":150,"categories":["Computer Science","Mathematics","Physics"],"accessUrl":"library.college.edu"}',
            isRead: false,
            isSent: true,
            sentAt: new Date('2024-01-17T14:00:00').toISOString(),
            readAt: null,
            createdAt: new Date('2024-01-17T14:00:00').toISOString(),
        },
        {
            title: 'Research Grant Application Deadline',
            message: 'Internal research grant applications due February 1. Submit proposals through research portal by 5:00 PM.',
            notificationType: 'warning',
            severity: 'medium',
            targetUserType: 'faculty',
            targetUserId: 5,
            referenceType: null,
            referenceId: null,
            metadata: '{"deadline":"2024-02-01T17:00:00","grantType":"internal","maxAmount":"Rs. 50,000","daysRemaining":11}',
            isRead: false,
            isSent: true,
            sentAt: new Date('2024-01-21T11:30:00').toISOString(),
            readAt: null,
            createdAt: new Date('2024-01-21T11:30:00').toISOString(),
        },
    ];

    await db.insert(notifications).values(sampleNotifications);
    
    console.log('✅ Notifications seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});