import { db } from '@/db';
import { timetable } from '@/db/schema';

async function main() {
    const sampleTimetable = [
        {
            facultyId: 1,
            subjectId: 1,
            classroomId: 1,
            dayOfWeek: 'Monday',
            startTime: '09:00',
            endTime: '10:00',
            semester: 'Semester 1',
            studentGroup: 'Group A',
            createdAt: new Date().toISOString(),
        },
        {
            facultyId: 2,
            subjectId: 3,
            classroomId: 2,
            dayOfWeek: 'Monday',
            startTime: '10:00',
            endTime: '11:00',
            semester: 'Semester 2',
            studentGroup: 'Group B',
            createdAt: new Date().toISOString(),
        },
        {
            facultyId: 3,
            subjectId: 5,
            classroomId: 3,
            dayOfWeek: 'Monday',
            startTime: '14:00',
            endTime: '15:00',
            semester: 'Semester 3',
            studentGroup: 'Group C',
            createdAt: new Date().toISOString(),
        },
        {
            facultyId: 4,
            subjectId: 7,
            classroomId: 4,
            dayOfWeek: 'Tuesday',
            startTime: '09:00',
            endTime: '10:00',
            semester: 'Semester 1',
            studentGroup: 'Group A',
            createdAt: new Date().toISOString(),
        },
        {
            facultyId: 5,
            subjectId: 9,
            classroomId: 5,
            dayOfWeek: 'Tuesday',
            startTime: '11:00',
            endTime: '12:00',
            semester: 'Semester 4',
            studentGroup: 'Group D',
            createdAt: new Date().toISOString(),
        },
        {
            facultyId: 6,
            subjectId: 11,
            classroomId: 6,
            dayOfWeek: 'Tuesday',
            startTime: '15:00',
            endTime: '16:00',
            semester: 'Semester 5',
            studentGroup: 'Group B',
            createdAt: new Date().toISOString(),
        },
        {
            facultyId: 7,
            subjectId: 13,
            classroomId: 7,
            dayOfWeek: 'Wednesday',
            startTime: '09:00',
            endTime: '10:00',
            semester: 'Semester 2',
            studentGroup: 'Group C',
            createdAt: new Date().toISOString(),
        },
        {
            facultyId: 8,
            subjectId: 15,
            classroomId: 8,
            dayOfWeek: 'Wednesday',
            startTime: '10:00',
            endTime: '11:00',
            semester: 'Semester 6',
            studentGroup: 'Group A',
            createdAt: new Date().toISOString(),
        },
        {
            facultyId: 9,
            subjectId: 2,
            classroomId: 9,
            dayOfWeek: 'Wednesday',
            startTime: '14:00',
            endTime: '15:00',
            semester: 'Semester 3',
            studentGroup: 'Group D',
            createdAt: new Date().toISOString(),
        },
        {
            facultyId: 10,
            subjectId: 4,
            classroomId: 10,
            dayOfWeek: 'Thursday',
            startTime: '09:00',
            endTime: '10:00',
            semester: 'Semester 1',
            studentGroup: 'Group B',
            createdAt: new Date().toISOString(),
        },
        {
            facultyId: 1,
            subjectId: 6,
            classroomId: 11,
            dayOfWeek: 'Thursday',
            startTime: '11:00',
            endTime: '12:00',
            semester: 'Semester 4',
            studentGroup: 'Group A',
            createdAt: new Date().toISOString(),
        },
        {
            facultyId: 2,
            subjectId: 8,
            classroomId: 12,
            dayOfWeek: 'Thursday',
            startTime: '16:00',
            endTime: '17:00',
            semester: 'Semester 2',
            studentGroup: 'Group C',
            createdAt: new Date().toISOString(),
        },
        {
            facultyId: 3,
            subjectId: 10,
            classroomId: 1,
            dayOfWeek: 'Friday',
            startTime: '09:00',
            endTime: '10:00',
            semester: 'Semester 5',
            studentGroup: 'Group D',
            createdAt: new Date().toISOString(),
        },
        {
            facultyId: 4,
            subjectId: 12,
            classroomId: 2,
            dayOfWeek: 'Friday',
            startTime: '10:00',
            endTime: '11:00',
            semester: 'Semester 3',
            studentGroup: 'Group A',
            createdAt: new Date().toISOString(),
        },
        {
            facultyId: 5,
            subjectId: 14,
            classroomId: 3,
            dayOfWeek: 'Friday',
            startTime: '14:00',
            endTime: '15:00',
            semester: 'Semester 6',
            studentGroup: 'Group B',
            createdAt: new Date().toISOString(),
        },
        {
            facultyId: 6,
            subjectId: 1,
            classroomId: 4,
            dayOfWeek: 'Saturday',
            startTime: '09:00',
            endTime: '10:00',
            semester: 'Semester 1',
            studentGroup: 'Group C',
            createdAt: new Date().toISOString(),
        },
        {
            facultyId: 7,
            subjectId: 3,
            classroomId: 5,
            dayOfWeek: 'Saturday',
            startTime: '11:00',
            endTime: '12:00',
            semester: 'Semester 4',
            studentGroup: 'Group D',
            createdAt: new Date().toISOString(),
        },
        {
            facultyId: 8,
            subjectId: 5,
            classroomId: 6,
            dayOfWeek: 'Monday',
            startTime: '12:00',
            endTime: '13:00',
            semester: 'Semester 2',
            studentGroup: 'Group A',
            createdAt: new Date().toISOString(),
        },
        {
            facultyId: 9,
            subjectId: 7,
            classroomId: 7,
            dayOfWeek: 'Tuesday',
            startTime: '16:00',
            endTime: '17:00',
            semester: 'Semester 5',
            studentGroup: 'Group B',
            createdAt: new Date().toISOString(),
        },
        {
            facultyId: 10,
            subjectId: 9,
            classroomId: 8,
            dayOfWeek: 'Wednesday',
            startTime: '12:00',
            endTime: '13:00',
            semester: 'Semester 3',
            studentGroup: 'Group C',
            createdAt: new Date().toISOString(),
        },
    ];

    await db.insert(timetable).values(sampleTimetable);
    
    console.log('✅ Timetable seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});